version: '3.8'
services:
  maven399java21:
    network_mode: bridge
    image: maven:3.9.9-eclipse-temurin-21-alpine
    container_name: maven399java21
    volumes:
      - ./:/app
    command: [ "/bin/sh", "-c", "apk update && apk add vim && sleep infinity" ]